apiVersion: v1
kind: Service
metadata:
  labels:
    app: accountpool
  name: accountpool
  namespace: crawler
spec:
  selector:
    app: accountpool
  ports:
    - port: 6777
      name: "6777"
      targetPort: 6777