apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxypool
  namespace: crawler
  labels:
    app: proxypool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxypool
  template:
    metadata:
      labels:
        app: proxypool
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: 'redis.crawler.svc.cluster.local'
            - name: REDIS_PORT
              value: '6379'
          image: tianmingboo/proxypool
          name: proxypool
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
            requests:
              memory: "500Mi"
              cpu: "300m"
          ports:
            - containerPort: 5555